name: easy_portainer

services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.26.0
    container_name: portainer
    restart: always
    ports:
      - ${PORT_UI:-9443}:9443
      - ${PORT_TUNNEL:-8000}:8000
    volumes:
      - ./volumes/data:/data
      - ${PATH_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
